export type Role = { title: string; dates: string; location?: string; summary?: string; achievements: string[]; technologies?: string[] };
export type Company = { name: string; description?: string; totalTenure?: string; roles: Role[]; tags?: string[] };
export type ExperienceChapter = { id: string; number: string; title: string; introduction: string; companies: Company[] };

export const profile = {
  name: 'Mario Sorgente', email: 'ms.sorgente@gmail.com', phone: '+31 687206252', location: 'The Randstad, Netherlands',
  linkedin: 'https://www.linkedin.com/in/mario-sorgente',
};
export const metrics = [['120%', 'Revenue growth delivered'], ['1,000+', 'Active users acquired'], ['99.8%', 'Platform uptime achieved'], ['95%', 'Additional market capacity unlocked'], ['20%', 'Faster time-to-market'], ['TRL 8', 'Hardware and software maturity reached']];
export const pillars = [
  ['Product Strategy', 'Vision, discovery, prioritisation, roadmaps, business models and go-to-market.'],
  ['AI Product Development', 'LLM workflows, AI agents, NLP, evaluation points, safeguards and human review.'],
  ['Platform & SaaS', 'Public APIs, RBAC, multitenancy, integrations, onboarding and scalable architecture.'],
];
export const chapters: ExperienceChapter[] = [
  { id:'leadership', number:'01', title:'Product Leadership & Platforms', introduction:'Leading complex SaaS and platform initiatives across AI, energy systems, integrations and internal product operations.', companies:[{
    name:'Sympower', description:'Energy flexibility and SaaS platform company.', totalTenure:'April 2023 – Present', tags:['SaaS','Public APIs','AI Adoption','RBAC','Energy','Platform Strategy','Multitenancy'], roles:[
      { title:'Senior Product Manager', dates:'January 2025 – Present', achievements:['Improved onboarding across multiple interfaces and user segments, accelerating time-to-market by 20%.','Drove organisational AI adoption through internal guides, tooling and governance policies.','Designed proofs of concept for AI products, including automated Java → Kotlin → Rust codebase migration.','Designed an internal GPT assistant for knowledge sharing, onboarding and collaboration.','Coached product managers on using AI in discovery, delivery and strategy.','Shaped the product vision for public APIs.','Defined and implemented role-based access control to reduce insider-trading risk.']},
      { title:'Product Manager', dates:'April 2023 – January 2025', location:'Amsterdam, Netherlands', achievements:['Grew the engineering team from 1 to 7 while leading product strategy from concept through implementation.','Increased integration release frequency from annually to quarterly.','Achieved 99.8% system uptime through reliable control and metering REST APIs.','Unlocked 95% additional market capacity through product packaging connecting renewable-energy assets across Europe.','Delivered 30% faster processing and reduced operational costs through a new SaaS architecture.','Led UX improvements and supported multitenant architecture across different frameworks.','Created a company-wide prioritisation system using Impact vs Effort, WSJF and ICE.','Introduced an opportunity solution tree connecting user problems to potential solutions.']}
    ]}]},
  { id:'founder', number:'02', title:'Founder-Led AI Products', introduction:'Taking AI-enabled products from initial insight to research, product design, engineering, launch and market validation.', companies:[
    { name:'Binderly', description:'Rapid LCA screening and decision support for concrete and cement sustainability.', roles:[{title:'Co-Founder',dates:'July 2025 – June 2026',summary:'Built with a civil engineer and LCA specialist to make sustainability decisions faster, transparent and accessible. Interest was validated with a civil-engineering association and C5Lab Portugal.',achievements:['Led product strategy, user research, PRDs, roadmap, UX/UI and full-stack implementation.','Built the data model and traceable LCA calculation engine for scenario comparison.','Created EPD Smart Parser, an NLP workflow turning EPD PDFs into auditable environmental data.','Designed an AI LCA Agent with contextual retrieval and human-in-the-loop review.','Delivered explainable assumptions and decision support aligned with relevant standards.'],technologies:['GitHub','Vercel','Supabase','GPT-5','Google Cloud','Codex','Cursor','Claude']}], tags:['AI Products','LLMs','Agents','Sustainability','0→1']},
    { name:'yourwAI', description:'AI-powered career matching based on skills, personality and goals.', roles:[{title:'Founder',dates:'March 2023 – December 2025',achievements:['Built and launched the platform from zero to one.','Used NLP and the OpenAI API to generate personalised career matching.','Reached more than 1,000 active users and 170 positive reviews within months.','Defined the business model, pricing and product strategy.','Led a cross-functional team from Double Diamond research through launch.','Used behaviour and feedback to guide iteration, A/B testing and growth.']}], tags:['B2C','NLP','User Research','Full-Stack Product']}
  ]},
  { id:'deep-tech', number:'03', title:'Deep-Tech Product Development', introduction:'Translating advanced sensing technology into scalable products, customer value and measurable commercial growth.', companies:[{
    name:'Optics11 — Fiber Optic Sensing Solutions', totalTenure:'February 2019 – April 2023', tags:['Deep Tech','Hardware + Software','TRL','International Markets','Fibre Optics'], roles:[
      {title:'Product Manager',dates:'May 2021 – April 2023',achievements:['Led a hardware and software product from MVP to TRL 8 within two years.','Increased revenue by 120% by identifying and addressing market needs.','Launched a product with 125% higher performance and 28% lower cost.','Led product branding, strategic repositioning and regulatory alignment.','Coordinated launches across 15+ contributors in EMEA, North America and APAC.','Managed full product-development cycles through Jira.']},
      {title:'Product Manager & Sales Engineer',dates:'January 2020 – May 2021',location:'Amsterdam, Netherlands',achievements:['Owned business development, product management and technical sales.','Converted leads into customers, contributing to 120% company revenue growth.','Worked with executives on roadmaps, pricing, portfolio strategy and positioning.','Prioritised launch activities, field tests and data analysis.','Identified product gaps and opportunities to improve market share and customer experience.']},
      {title:'Application Engineer',dates:'February 2019 – January 2020',location:'Amsterdam, Netherlands',achievements:['Built test setups integrating sensing hardware and software.','Delivered user training, technical support and customer installations.','Demonstrated sensing across civil, medical, energy and underwater applications.','Managed suppliers and analysed data with MATLAB and LabVIEW.']}
    ]}]},
  { id:'foundations', number:'04', title:'Engineering Foundations', introduction:'An engineering foundation in photonics, electronics, materials and experimental product development.', companies:[{
    name:'STMicroelectronics', description:'Smart Power division', roles:[{title:'PCM Memory Engineer Intern',dates:'May 2018 – December 2018',location:'Agrate Brianza, Italy',achievements:['Characterised Phase Change Memory and analysed materials.','Evaluated temperature response and memory-embedding challenges.','Produced technical reports using LaTeX.']}], tags:['Semiconductors','Materials','Electronics','R&D']
  }]}
];
export const expertise = [
 ['AI & Intelligent Products',['AI product strategy','LLM-powered workflows','AI agent design','Prompt engineering','NLP','Human-in-the-loop systems','AI governance','Evaluation and safeguards']],
 ['Product Leadership',['Product vision','Discovery','Roadmapping','Prioritisation','Opportunity solution trees','Cross-functional leadership','Product-market fit','Go-to-market strategy']],
 ['Platforms & SaaS',['Public APIs','REST APIs','RBAC','Multitenancy','Integrations','SaaS architecture','Onboarding','Platform reliability']],
 ['Commercial & Delivery',['Pricing','Product packaging','Technical sales','Market research','A/B testing','Product launches','International markets','Agile delivery']]
] as const;
export const education = [
 ['Politecnico di Milano','Master of Science','Physics Engineering — Photonics and Nano Optics','2016 – 2018'],['Politecnico di Milano','Bachelor’s Degree','Electronics','2013 – 2016'],['Udacity','AI Product Manager Nanodegree','Artificial Intelligence','2021'],['IIS J.C. Maxwell','Aeronautical Technical Diploma','Aerospace, Aeronautical and Astronautical Engineering','2006 – 2011']
];
export const languages = [['English','Native or bilingual'],['Italian','Native or bilingual'],['Spanish','Limited working'],['Dutch','Elementary']];
export const certifications = ['Achieving Product-Market Fit','Body Language for Leaders','Excel for Sales Professionals','Effective Business Writing','Techniques for Non-Native Writers','Negotiation Skills'];
export const publications = ['Characterization of Biocomposites and Glass Fiber Epoxy Composites Based on Acoustic Emission Signals, Deep Feature Extraction, and Machine Learning','Performance Comparison between FO and PZT AE Sensors','ChatGPT in Product Management','Structural Health Monitoring for Aerospace Application'];
